### ISSUE TITLE
这个全局GlobalKey怎么设置的呀！！！ 求解答下

### ISSUE THREAD

**Issue by lp7799** [inRush/TipDialog#1]

**Comment by lp7799** [comment]
这个全局GlobalKey怎么设置的呀！！！ 求解答下

**Comment by inRush** [comment]
在最新版里不太推荐用GlobalKey，因为在全局使用TipDialog的时候，GlobalKey不好，也很麻烦，推荐用TipDialogConnector来获取Controller来进行控制，如果你必须得用GlobalKey的话，可以看我的commit记录，里面有我之前用GlobalKey的代码
[commit记录](https://github.com/inRush/TipDialog/commit/a640117ebb70e34faff095c849277dcbe25cffcc)
