### ISSUE TITLE
[Request] Click to dismiss

### ISSUE THREAD

**Issue by jasonlaw** [inRush/TipDialog#10]
Can I request to have click to dismiss functionality?
I want to set the dismiss duration to 5 second, but user can click the screen to dismiss the dialog.
Thanks.

**Comment by inRush** [comment]
@jasonlaw Thank you for your suggestion. I will add it as soon as possible

**Comment by inRush** [comment]
hi @jasonlaw , i publish a new version 3.1.0, you can use the following interface for configuration
```
// outside touchable, default false
// if true and onOutsideTouch not set, when use TipDialogHelper.loading(), you can touch mask layer to dismiss
// if true and onOutsideTouch set, when touching the mask layer, onOutsideTouch will be called.
this.outsideTouchable: false
// outside touch callback {@link OutsideTouchCallback}
this.onOutsideTouch
```
