### ISSUE TITLE
Not working in web

### ISSUE THREAD

**Issue by jasonlaw** [inRush/TipDialog#11]
Hi @inRush ,

The package works great in mobile, but not in web. Could you please help?

Mobile
![tipdialog-mobile](https://user-images.githubusercontent.com/107820/73907433-38711d00-48e1-11ea-95cc-d77cad7a96f8.gif)

Web
![tipdialog-web](https://user-images.githubusercontent.com/107820/73907435-3ad37700-48e1-11ea-9feb-7d031970289d.gif)

**Comment by inRush** [comment]
I haven't tried it on the web before. In the next release I'll make it fit on the web side

**Comment by inRush** [comment]
@jasonlaw

**Comment by jasonlaw** [comment]
> I haven't tried it on the web before. In the next release I'll make it fit on the web side

Thank you very much!

**Comment by jasonlaw** [comment]
It seems due to a bug in my code, sorry about that, I will close this now. Thanks anyway. :)
