### ISSUE TITLE
Unhandled error setState() called after dispose(): TipDialogContainerState

### ISSUE THREAD

**Issue by chitgoks** [inRush/TipDialog#12]
Hi. i wish to ask. what if i have 2 window

Let's say window 1 has TipDialogContainer().
it clicks a button and opens window 2. I also place TipDialogContainer() here and if tip dialog shows up, it works ok.

i close window 2. then do operations in window 1, when tip dialog shows, it shows this error message

```

Unhandled Exception: Unhandled error setState() called after dispose(): TipDialogContainerState#45379(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
E/flutter (23406): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (23406): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
```

The TipDialogHelper uses only 1 state and accesses it through its static variable. perhaps when the new window is closed, the state is killed off, there by when window 1 uses it, the static state has already been disposed which results in this error?

Any workarounds? thank you

**Comment by jjacquesf** [comment]
You can use the builder option for MaterialApp to enable TipDialog support and remove it from other widgets. 
`
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return ProviderBloc(
        child: MaterialApp(
          title: 'Material App',
          debugShowCheckedModeBanner: false,
          // home: ProductsPage(),
          initialRoute: 'home',
          routes: getApplicationRoutes(),
          onUnknownRoute: ( RouteSettings settings ) {        
            return MaterialPageRoute(
              builder: (context) => HomePage()
            );
          },
          builder: (context, widget) {
            return Stack(
              children: <Widget> [
                widget,
                TipDialogContainer(
                  duration: const Duration(seconds: 2),
                  outsideTouchable: true,
                  onOutsideTouch: (Widget tipDialog) {
                    if (tipDialog is TipDialog &&
                        tipDialog.type == TipDialogType.LOADING) {
                      TipDialogHelper.dismiss();
                    }
                })
              ]
            );
          },
      ),
    );
  }
}
`
