### ISSUE TITLE
TipDialog and loading_view doesn't support null safety

### ISSUE THREAD

**Issue by segungreat** [inRush/TipDialog#13]
I installed the latest version as explained  in the readme.

When i run my app, it shows 

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:tip_dialog
 - package:loading_view

any solution to this

**Comment by inRush** [comment]
please upgrade tipDialog version to 4.0.0 or run `dart pub upgrade --null-safety`
