### ISSUE TITLE
Type为LOADING状态时，isLoading不起效，还是会默认三秒后消失

### ISSUE THREAD

**Issue by didyqian** [inRush/TipDialog#2]
Type为LOADING状态时，isLoading不起效，还是会默认三秒后消失,
我运行demo测试了一下，把isLoading设置为true，然后运行Type为LOADING，能整成不消失的显示，但是再运行别的类型之后，会不停调用dimiss方法。

**Comment by inRush** [comment]
@didyqian 在new Container设置Type为LOADING的时候，会自动设置isLoading为true，但是在调用show方法设置的Type为LOADING的时候，不会自动设置isLoading为true，需要手动设置为true，而内部判断是否自动消失就是根据这个isLoading的值判定的，true的时候不会自动消失，false的时候会自动消失，这个自动消失的时间可以在 new Container的时候设置，其实这个值应该叫isAutoDismiss会好一点

**你说的不停调用dismiss的情况有复现代码么？我这里复现不出来**

**Comment by didyqian** [comment]
> @didyqian 在new Container设置Type为LOADING的时候，会自动设置isLoading为true，但是在调用show方法设置的Type为LOADING的时候，不会自动设置isLoading为true，需要手动设置为true，而内部判断是否自动消失就是根据这个isLoading的值判定的，true的时候不会自动消失，false的时候会自动消失，这个自动消失的时间可以在 new Container的时候设置，其实这个值应该叫isAutoDismiss会好一点
> 
> **你说的不停调用dismiss的情况有复现代码么？我这里复现不出来**

我下载了demo直接运行的，在tip_dialog,dart里面的dismiss方法加了log打印，发现dialog显示过一次之后，就会不停调用dismiss。

**Comment by didyqian** [comment]
> @didyqian 在new Container设置Type为LOADING的时候，会自动设置isLoading为true，但是在调用show方法设置的Type为LOADING的时候，不会自动设置isLoading为true，需要手动设置为true，而内部判断是否自动消失就是根据这个isLoading的值判定的，true的时候不会自动消失，false的时候会自动消失，这个自动消失的时间可以在 new Container的时候设置，其实这个值应该叫isAutoDismiss会好一点
> 
> **你说的不停调用dismiss的情况有复现代码么？我这里复现不出来**

好像是timer那个部分出了问题 不停循环了

**Comment by didyqian** [comment]
> @didyqian 在new Container设置Type为LOADING的时候，会自动设置isLoading为true，但是在调用show方法设置的Type为LOADING的时候，不会自动设置isLoading为true，需要手动设置为true，而内部判断是否自动消失就是根据这个isLoading的值判定的，true的时候不会自动消失，false的时候会自动消失，这个自动消失的时间可以在 new Container的时候设置，其实这个值应该叫isAutoDismiss会好一点
> 
> **你说的不停调用dismiss的情况有复现代码么？我这里复现不出来**

代码里timer的回调没有运行_timer.cancel();取消timer，导致不停调用了，

**Comment by inRush** [comment]
> > @didyqian 在new Container设置Type为LOADING的时候，会自动设置isLoading为true，但是在调用show方法设置的Type为LOADING的时候，不会自动设置isLoading为true，需要手动设置为true，而内部判断是否自动消失就是根据这个isLoading的值判定的，true的时候不会自动消失，false的时候会自动消失，这个自动消失的时间可以在 new Container的时候设置，其实这个值应该叫isAutoDismiss会好一点
> > **你说的不停调用dismiss的情况有复现代码么？我这里复现不出来**
> 
> 代码里timer的回调没有运行_timer.cancel();取消timer，导致不停调用了，

😃感谢指正，😂太粗心了，导致了这个Bug
