### ISSUE TITLE
How to show the TipDialog in the initState.

### ISSUE THREAD

**Issue by davidhsu1115** [inRush/TipDialog#6]
As title.
How can I show the TipDialog in the initState.
I want to show the TipDialog when the page is pushed, and dismiss the TipDialog when the data has been downloaded.

**Comment by inRush** [comment]
hello, you can use FutureBuilder to build the page root widget, such as
``` dart
new FutureBuilder<List<MessageModel>>(
          future: getData(messages), // this method return a Future
          builder: (context, snapshot) {

        if (snapshot.connectionState == ConnectionState.active ||
            snapshot.connectionState == ConnectionState.waiting) {
          return new TipDialogConnector(); // show tip dialog
        }
        if (snapshot.connectionState == ConnectionState.done) {
          if (snapshot.hasError) {
            return new Container() // show error message
          } else if (snapshot.hasData) {
            return new Container(); // show content
          }
        }
     })
```

**Comment by inRush** [comment]
> As title.
> How can I show the TipDialog in the initState.
> I want to show the TipDialog when the page is pushed, and dismiss the TipDialog when the data has been downloaded.

I hope that the method I mentioned above can help you.

**Comment by davidhsu1115** [comment]
Thanks! 
Actually I was just thinking about using FutureBuilder just don't know how to implement it.
Your answer helps a lot.
