### ISSUE TITLE
TipDialog 的显示和隐藏方法调用间隔太短，导致界面不可点击【可能】

### ISSUE THREAD

**Issue by luxunchina** [inRush/TipDialog#7]
1、在点击事件中，我先调用TipDIalog的显示方法，然后请求网络接口，接口回调内，隐藏TipDialog，然后我就一直点击这个按钮，结果在TipDialog隐藏后，界面就不响应任何触摸事件了。

2、后来我在网络请求方法之前，加入了一个延时操作，即调用TipDialog的显示方法后，延时500MS调用网络接口，然后一直点击按钮，这个现象就一直没有出现，一切正常。

个人猜测是网络请求过快，相当于TipDialog的Show方法刚调用完就调用了Dissmiss，会不是这样导致了这个问题，只有这样才能解释为什么我加了一个延时后就正常了。

**Comment by luxunchina** [comment]
真机是Android 7.0 ，虚拟机是iphone X。

**Comment by inRush** [comment]
@luxunchina  已修复
