### ISSUE TITLE
协议是 GPL 也太狠了吧

### ISSUE THREAD

**Issue by xalanq** [inRush/TipDialog#9]
兄弟，望三思哈哈哈哈哈哈哈哈

这样很多人不太敢用你的库（

MIT、Apache 它不香吗

**Comment by inRush** [comment]
@xalanq 哈哈哈，我想了下，也是，开始的时候就想的太单纯了些，我这小库也不是什么厉害的东西，还是改成宽松的协议好了。
谢谢兄弟给的意见哈。
